### ISSUE TITLE
It doesn't work well with webpack.

### ISSUE THREAD

**Issue by alexserver** [fffunction/please#4]
I was following basic instructions
into an index.jsx file:

```
var fabric = require('please-ajax')(window);
```

And publishing it with webpack.
I had the following error:

```
Uncaught TypeError: __webpack_require__(...) is not a function
```

in:

```
var please = __webpack_require__(5)(window);
```

**Comment by danreeves** [comment]
I'm not sure how webpack resolves modules, can you try it without the `(window)`. If that doesn't work can you give me your config so I can reproduce? 
Thanks

**Comment by danreeves** [comment]
@alexserver I've just release a new version. I couldn't get it to work with webpack, so I changed the way the module is initialised.

``` js
var fabric = require('please-ajax');
```

We can close this issue if you confirm it works for you.

**Comment by danreeves** [comment]
Assuming no more issue
