### ISSUE TITLE
IE9 error: Invalid argument.

### ISSUE THREAD

**Issue by baptistebriel** [fffunction/please#5]
Hello, looks like `please-ajax` isn't working properly in IE9. Here's a screenshot of the error.

![screen shot 2015-10-22 at 17 03 11](https://cloud.githubusercontent.com/assets/2464663/10668965/e956df92-78de-11e5-82c8-3c1a91f82953.png)

I tried with jQuery's `ajax` and it works. Thanks!

**Comment by danreeves** [comment]
Hi @baptistebriel,

What kind of data are you passing in? `please-ajax` expects the [same inputs as native xhr](http://devdocs.io/dom/xmlhttprequest#send%28%29) and doesn't `JSON.stringify` objects for you. 

Example usage:

``` js
plz.post('http://example.com/api', JSON.stringify(yourObject), { ... });
```

**Comment by baptistebriel** [comment]
I am actually just doing a GET to return some HTML, basically a request to a WordPress URL.
So I guess I don't need to `JSON.stringify` anything.

Thanks!

**Comment by danreeves** [comment]
Cool, so passing in data to a GET should maybe be prevented to stop IE9 panicking.

**Comment by baptistebriel** [comment]
Actually, I'm already doing a GET request:

``` javascript
ajax.get('/' + slug, {
  success: (object) => {
    page.innerHTML = object.data;
  }
});
```

...and still have the error in IE9. Any ideas? Thanks for the help!

**Comment by danreeves** [comment]
I'll look into it.

Maybe I should be passing in `undefined` rather than `false`, https://github.com/fffunction/please/blob/master/src/please.js#L125

**Comment by baptistebriel** [comment]
Cool, I submitted a PR.
Thanks a lot @danreeves !

**Comment by danreeves** [comment]
Thanks @baptistebriel. A new release (2.0.1) has been published to npm
